# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/semaphore-api/semaphore-codegen.git
"""


from __future__ import absolute_import

import unittest

import semaphore_client
from semaphore_client import APIToken
from semaphore_client.models.login import Login  # noqa: E501
from semaphore_client.rest import ApiException

from semaphore_client.semaphore_helper import SemaphoreHelper


class TestLogin(unittest.TestCase):
    """Login unit test stubs"""

    def setUp(self):
        self.semaphore_base_url = 'http://localhost:3000/api'
        if SemaphoreHelper.service_is_up(self.semaphore_base_url):
            self.username = 'admin'
            self.password = 'password'

    def tearDown(self):
        pass

    def testLogin(self):
        """Test Login"""
        if SemaphoreHelper.service_is_up(self.semaphore_base_url):
            self.helper = SemaphoreHelper(self.semaphore_base_url, self.username, self.password)



if __name__ == '__main__':
    unittest.main()
