# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/semaphore-api/semaphore-codegen.git
"""


from __future__ import absolute_import

import unittest

import semaphore_client
from semaphore_client.api.default_api import DefaultApi  # noqa: E501
from semaphore_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = semaphore_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_events_get(self):
        """Test case for events_get

        Get Events related to Semaphore and projects you are part of  # noqa: E501
        """
        pass

    def test_events_last_get(self):
        """Test case for events_last_get

        Get last 200 Events related to Semaphore and projects you are part of  # noqa: E501
        """
        pass

    def test_info_get(self):
        """Test case for info_get

        Fetches information about semaphore  # noqa: E501
        """
        pass

    def test_ping_get(self):
        """Test case for ping_get

        PING test  # noqa: E501
        """
        pass

    def test_upgrade_get(self):
        """Test case for upgrade_get

        Check if new updates available and fetch /info  # noqa: E501
        """
        pass

    def test_upgrade_post(self):
        """Test case for upgrade_post

        Upgrade the server  # noqa: E501
        """
        pass

    def test_ws_get(self):
        """Test case for ws_get

        Websocket handler  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
