# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/semaphore-api/semaphore-codegen.git
"""


from __future__ import absolute_import

import unittest

import semaphore_client
from semaphore_client.models.environment_request import EnvironmentRequest  # noqa: E501
from semaphore_client.rest import ApiException


class TestEnvironmentRequest(unittest.TestCase):
    """EnvironmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvironmentRequest(self):
        """Test EnvironmentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = semaphore_client.models.environment_request.EnvironmentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
