# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/semaphore-api/semaphore-codegen.git
"""


from __future__ import absolute_import

import unittest

import semaphore_client
from semaphore_client.models.task import Task  # noqa: E501
from semaphore_client.rest import ApiException


class TestTask(unittest.TestCase):
    """Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTask(self):
        """Test Task"""
        # FIXME: construct object with mandatory attributes with example values
        # model = semaphore_client.models.task.Task()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
