# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/semaphore-api/semaphore-codegen.git
"""


from __future__ import absolute_import

import unittest

import semaphore_client
from semaphore_client.models.info_type_update import InfoTypeUpdate  # noqa: E501
from semaphore_client.rest import ApiException


class TestInfoTypeUpdate(unittest.TestCase):
    """InfoTypeUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInfoTypeUpdate(self):
        """Test InfoTypeUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = semaphore_client.models.info_type_update.InfoTypeUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
