# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/semaphore-api/semaphore-codegen.git
"""


from __future__ import absolute_import

import unittest

import semaphore_client
from semaphore_client.api.projects_api import ProjectsApi  # noqa: E501
from semaphore_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = semaphore_client.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_projects_get(self):
        """Test case for projects_get

        Get projects  # noqa: E501
        """
        pass

    def test_projects_post(self):
        """Test case for projects_post

        Create a new project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
