# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AccessKeyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'project_id': 'int',
        'key': 'str',
        'secret': 'str'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'project_id': 'project_id',
        'key': 'key',
        'secret': 'secret'
    }

    def __init__(self, name=None, type=None, project_id=None, key=None, secret=None):  # noqa: E501
        """AccessKeyRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._type = None
        self._project_id = None
        self._key = None
        self._secret = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if project_id is not None:
            self.project_id = project_id
        if key is not None:
            self.key = key
        if secret is not None:
            self.secret = secret

    @property
    def name(self):
        """Gets the name of this AccessKeyRequest.  # noqa: E501


        :return: The name of this AccessKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AccessKeyRequest.


        :param name: The name of this AccessKeyRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this AccessKeyRequest.  # noqa: E501


        :return: The type of this AccessKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AccessKeyRequest.


        :param type: The type of this AccessKeyRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["ssh", "aws", "gcloud", "do"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def project_id(self):
        """Gets the project_id of this AccessKeyRequest.  # noqa: E501


        :return: The project_id of this AccessKeyRequest.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this AccessKeyRequest.


        :param project_id: The project_id of this AccessKeyRequest.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def key(self):
        """Gets the key of this AccessKeyRequest.  # noqa: E501


        :return: The key of this AccessKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this AccessKeyRequest.


        :param key: The key of this AccessKeyRequest.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def secret(self):
        """Gets the secret of this AccessKeyRequest.  # noqa: E501


        :return: The secret of this AccessKeyRequest.  # noqa: E501
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this AccessKeyRequest.


        :param secret: The secret of this AccessKeyRequest.  # noqa: E501
        :type: str
        """

        self._secret = secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccessKeyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccessKeyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
