# coding: utf-8

"""
    SEMAPHORE

    Semaphore API  # noqa: E501

    OpenAPI spec version: 2.2.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TaskOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task_id': 'int',
        'task': 'str',
        'time': 'datetime',
        'output': 'str'
    }

    attribute_map = {
        'task_id': 'task_id',
        'task': 'task',
        'time': 'time',
        'output': 'output'
    }

    def __init__(self, task_id=None, task=None, time=None, output=None):  # noqa: E501
        """TaskOutput - a model defined in Swagger"""  # noqa: E501
        self._task_id = None
        self._task = None
        self._time = None
        self._output = None
        self.discriminator = None
        if task_id is not None:
            self.task_id = task_id
        if task is not None:
            self.task = task
        if time is not None:
            self.time = time
        if output is not None:
            self.output = output

    @property
    def task_id(self):
        """Gets the task_id of this TaskOutput.  # noqa: E501


        :return: The task_id of this TaskOutput.  # noqa: E501
        :rtype: int
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this TaskOutput.


        :param task_id: The task_id of this TaskOutput.  # noqa: E501
        :type: int
        """

        self._task_id = task_id

    @property
    def task(self):
        """Gets the task of this TaskOutput.  # noqa: E501


        :return: The task of this TaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this TaskOutput.


        :param task: The task of this TaskOutput.  # noqa: E501
        :type: str
        """

        self._task = task

    @property
    def time(self):
        """Gets the time of this TaskOutput.  # noqa: E501


        :return: The time of this TaskOutput.  # noqa: E501
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this TaskOutput.


        :param time: The time of this TaskOutput.  # noqa: E501
        :type: datetime
        """

        self._time = time

    @property
    def output(self):
        """Gets the output of this TaskOutput.  # noqa: E501


        :return: The output of this TaskOutput.  # noqa: E501
        :rtype: str
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TaskOutput.


        :param output: The output of this TaskOutput.  # noqa: E501
        :type: str
        """

        self._output = output

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
