# coding: utf-8

"""
    Polemarch

     ### Polemarch is ansible based service for orchestration infrastructure.  * [Documentation](http://polemarch.readthedocs.io/) * [Issue Tracker](https://gitlab.com/vstconsulting/polemarch/issues) * [Source Code](https://gitlab.com/vstconsulting/polemarch)    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OneGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'notes': 'str',
        'children': 'bool',
        'owner': 'User'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'notes': 'notes',
        'children': 'children',
        'owner': 'owner'
    }

    def __init__(self, id=None, name=None, notes=None, children=None, owner=None):  # noqa: E501
        """OneGroup - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._notes = None
        self._children = None
        self._owner = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if notes is not None:
            self.notes = notes
        if children is not None:
            self.children = children
        if owner is not None:
            self.owner = owner

    @property
    def id(self):
        """Gets the id of this OneGroup.  # noqa: E501


        :return: The id of this OneGroup.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OneGroup.


        :param id: The id of this OneGroup.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this OneGroup.  # noqa: E501


        :return: The name of this OneGroup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OneGroup.


        :param name: The name of this OneGroup.  # noqa: E501
        :type: str
        """
        if name is not None and len(name) > 512:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `512`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def notes(self):
        """Gets the notes of this OneGroup.  # noqa: E501


        :return: The notes of this OneGroup.  # noqa: E501
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes):
        """Sets the notes of this OneGroup.


        :param notes: The notes of this OneGroup.  # noqa: E501
        :type: str
        """

        self._notes = notes

    @property
    def children(self):
        """Gets the children of this OneGroup.  # noqa: E501


        :return: The children of this OneGroup.  # noqa: E501
        :rtype: bool
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this OneGroup.


        :param children: The children of this OneGroup.  # noqa: E501
        :type: bool
        """

        self._children = children

    @property
    def owner(self):
        """Gets the owner of this OneGroup.  # noqa: E501


        :return: The owner of this OneGroup.  # noqa: E501
        :rtype: User
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this OneGroup.


        :param owner: The owner of this OneGroup.  # noqa: E501
        :type: User
        """

        self._owner = owner

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OneGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OneGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
