# coding: utf-8

"""
    Polemarch

     ### Polemarch is ansible based service for orchestration infrastructure.  * [Documentation](http://polemarch.readthedocs.io/) * [Issue Tracker](https://gitlab.com/vstconsulting/polemarch/issues) * [Source Code](https://gitlab.com/vstconsulting/polemarch)    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import polemarch_client
from polemarch_client.api.inventory_api import InventoryApi  # noqa: E501
from polemarch_client.rest import ApiException


class TestInventoryApi(unittest.TestCase):
    """InventoryApi unit test stubs"""

    def setUp(self):
        self.api = polemarch_client.api.inventory_api.InventoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inventory_add(self):
        """Test case for inventory_add

        """
        pass

    def test_inventory_all_groups_get(self):
        """Test case for inventory_all_groups_get

        """
        pass

    def test_inventory_all_groups_list(self):
        """Test case for inventory_all_groups_list

        """
        pass

    def test_inventory_all_hosts_get(self):
        """Test case for inventory_all_hosts_get

        """
        pass

    def test_inventory_all_hosts_list(self):
        """Test case for inventory_all_hosts_list

        """
        pass

    def test_inventory_copy(self):
        """Test case for inventory_copy

        """
        pass

    def test_inventory_edit(self):
        """Test case for inventory_edit

        """
        pass

    def test_inventory_get(self):
        """Test case for inventory_get

        """
        pass

    def test_inventory_group_add(self):
        """Test case for inventory_group_add

        """
        pass

    def test_inventory_group_copy(self):
        """Test case for inventory_group_copy

        """
        pass

    def test_inventory_group_edit(self):
        """Test case for inventory_group_edit

        """
        pass

    def test_inventory_group_get(self):
        """Test case for inventory_group_get

        """
        pass

    def test_inventory_group_list(self):
        """Test case for inventory_group_list

        """
        pass

    def test_inventory_group_remove(self):
        """Test case for inventory_group_remove

        """
        pass

    def test_inventory_group_set_owner(self):
        """Test case for inventory_group_set_owner

        """
        pass

    def test_inventory_group_update(self):
        """Test case for inventory_group_update

        """
        pass

    def test_inventory_group_variables_add(self):
        """Test case for inventory_group_variables_add

        """
        pass

    def test_inventory_group_variables_edit(self):
        """Test case for inventory_group_variables_edit

        """
        pass

    def test_inventory_group_variables_get(self):
        """Test case for inventory_group_variables_get

        """
        pass

    def test_inventory_group_variables_list(self):
        """Test case for inventory_group_variables_list

        """
        pass

    def test_inventory_group_variables_remove(self):
        """Test case for inventory_group_variables_remove

        """
        pass

    def test_inventory_group_variables_update(self):
        """Test case for inventory_group_variables_update

        """
        pass

    def test_inventory_host_add(self):
        """Test case for inventory_host_add

        """
        pass

    def test_inventory_host_copy(self):
        """Test case for inventory_host_copy

        """
        pass

    def test_inventory_host_edit(self):
        """Test case for inventory_host_edit

        """
        pass

    def test_inventory_host_get(self):
        """Test case for inventory_host_get

        """
        pass

    def test_inventory_host_list(self):
        """Test case for inventory_host_list

        """
        pass

    def test_inventory_host_remove(self):
        """Test case for inventory_host_remove

        """
        pass

    def test_inventory_host_set_owner(self):
        """Test case for inventory_host_set_owner

        """
        pass

    def test_inventory_host_update(self):
        """Test case for inventory_host_update

        """
        pass

    def test_inventory_host_variables_add(self):
        """Test case for inventory_host_variables_add

        """
        pass

    def test_inventory_host_variables_edit(self):
        """Test case for inventory_host_variables_edit

        """
        pass

    def test_inventory_host_variables_get(self):
        """Test case for inventory_host_variables_get

        """
        pass

    def test_inventory_host_variables_list(self):
        """Test case for inventory_host_variables_list

        """
        pass

    def test_inventory_host_variables_remove(self):
        """Test case for inventory_host_variables_remove

        """
        pass

    def test_inventory_host_variables_update(self):
        """Test case for inventory_host_variables_update

        """
        pass

    def test_inventory_import_inventory(self):
        """Test case for inventory_import_inventory

        """
        pass

    def test_inventory_list(self):
        """Test case for inventory_list

        """
        pass

    def test_inventory_remove(self):
        """Test case for inventory_remove

        """
        pass

    def test_inventory_set_owner(self):
        """Test case for inventory_set_owner

        """
        pass

    def test_inventory_update(self):
        """Test case for inventory_update

        """
        pass

    def test_inventory_variables_add(self):
        """Test case for inventory_variables_add

        """
        pass

    def test_inventory_variables_edit(self):
        """Test case for inventory_variables_edit

        """
        pass

    def test_inventory_variables_get(self):
        """Test case for inventory_variables_get

        """
        pass

    def test_inventory_variables_list(self):
        """Test case for inventory_variables_list

        """
        pass

    def test_inventory_variables_remove(self):
        """Test case for inventory_variables_remove

        """
        pass

    def test_inventory_variables_update(self):
        """Test case for inventory_variables_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
