# coding: utf-8

"""
    Polemarch

     ### Polemarch is ansible based service for orchestration infrastructure.  * [Documentation](http://polemarch.readthedocs.io/) * [Issue Tracker](https://gitlab.com/vstconsulting/polemarch/issues) * [Source Code](https://gitlab.com/vstconsulting/polemarch)    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import polemarch_client
from polemarch_client.models.create_user import CreateUser  # noqa: E501
from polemarch_client.rest import ApiException


class TestCreateUser(unittest.TestCase):
    """CreateUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUser(self):
        """Test CreateUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = polemarch_client.models.create_user.CreateUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
