# coding: utf-8

"""
    Polemarch

     ### Polemarch is ansible based service for orchestration infrastructure.  * [Documentation](http://polemarch.readthedocs.io/) * [Issue Tracker](https://gitlab.com/vstconsulting/polemarch/issues) * [Source Code](https://gitlab.com/vstconsulting/polemarch)    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import polemarch_client
from polemarch_client.api.hook_api import HookApi  # noqa: E501
from polemarch_client.rest import ApiException


class TestHookApi(unittest.TestCase):
    """HookApi unit test stubs"""

    def setUp(self):
        self.api = polemarch_client.api.hook_api.HookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hook_add(self):
        """Test case for hook_add

        """
        pass

    def test_hook_edit(self):
        """Test case for hook_edit

        """
        pass

    def test_hook_get(self):
        """Test case for hook_get

        """
        pass

    def test_hook_list(self):
        """Test case for hook_list

        """
        pass

    def test_hook_remove(self):
        """Test case for hook_remove

        """
        pass

    def test_hook_update(self):
        """Test case for hook_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
