# coding: utf-8

"""
    Polemarch

     ### Polemarch is ansible based service for orchestration infrastructure.  * [Documentation](http://polemarch.readthedocs.io/) * [Issue Tracker](https://gitlab.com/vstconsulting/polemarch/issues) * [Source Code](https://gitlab.com/vstconsulting/polemarch)    # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import polemarch_client
from polemarch_client.api.history_api import HistoryApi  # noqa: E501
from polemarch_client.rest import ApiException


class TestHistoryApi(unittest.TestCase):
    """HistoryApi unit test stubs"""

    def setUp(self):
        self.api = polemarch_client.api.history_api.HistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_history_cancel(self):
        """Test case for history_cancel

        """
        pass

    def test_history_clear(self):
        """Test case for history_clear

        """
        pass

    def test_history_facts(self):
        """Test case for history_facts

        """
        pass

    def test_history_get(self):
        """Test case for history_get

        """
        pass

    def test_history_list(self):
        """Test case for history_list

        """
        pass

    def test_history_remove(self):
        """Test case for history_remove

        """
        pass


if __name__ == '__main__':
    unittest.main()
