# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sure_tosca.models.base_model_ import Model
from sure_tosca import util


class ToscaTemplate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, items=None, additional_properties=None):  # noqa: E501
        """ToscaTemplate - a model defined in Swagger

        :param items: The items of this ToscaTemplate.  # noqa: E501
        :type items: str
        :param additional_properties: The additional_properties of this ToscaTemplate.  # noqa: E501
        :type additional_properties: object
        """
        self.swagger_types = {
            'items': str,
            'additional_properties': object
        }

        self.attribute_map = {
            'items': 'items',
            'additional_properties': 'additionalProperties'
        }

        self._items = items
        self._additional_properties = additional_properties

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ToscaTemplate of this ToscaTemplate.  # noqa: E501
        :rtype: ToscaTemplate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this ToscaTemplate.


        :return: The items of this ToscaTemplate.
        :rtype: str
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this ToscaTemplate.


        :param items: The items of this ToscaTemplate.
        :type items: str
        """

        self._items = items

    @property
    def additional_properties(self):
        """Gets the additional_properties of this ToscaTemplate.


        :return: The additional_properties of this ToscaTemplate.
        :rtype: object
        """
        return self._additional_properties

    @additional_properties.setter
    def additional_properties(self, additional_properties):
        """Sets the additional_properties of this ToscaTemplate.


        :param additional_properties: The additional_properties of this ToscaTemplate.
        :type additional_properties: object
        """

        self._additional_properties = additional_properties
