# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from nl.sne.sure_tosca.models.base_model_ import Model
from nl.sne.sure_tosca import util


class Credentials(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, additional_properties=None):  # noqa: E501
        """Credentials - a model defined in Swagger

        :param additional_properties: The additional_properties of this Credentials.  # noqa: E501
        :type additional_properties: str
        """
        self.swagger_types = {
            'additional_properties': str
        }

        self.attribute_map = {
            'additional_properties': 'additionalProperties'
        }

        self._additional_properties = additional_properties

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Credentials of this Credentials.  # noqa: E501
        :rtype: Credentials
        """
        return util.deserialize_model(dikt, cls)

    @property
    def additional_properties(self):
        """Gets the additional_properties of this Credentials.


        :return: The additional_properties of this Credentials.
        :rtype: str
        """
        return self._additional_properties

    @additional_properties.setter
    def additional_properties(self, additional_properties):
        """Sets the additional_properties of this Credentials.


        :param additional_properties: The additional_properties of this Credentials.
        :type additional_properties: str
        """

        self._additional_properties = additional_properties
